Refactored data extraction and extended news sources
c2siorg/b0bot pull request #25
Opened 2024-06-23 05:34 UTC by hardik1408

## Description

- New sources have been added from where data is being extracted. redundant sources have been removed and unneccessary categories have been reomved. 
- The sources have now been shifted to a separate json file in order to improve the overall readability of the code.
- Data extraction process has been refactored.
- Data is being filtered out before adding it to the database.
- Duplicate values are being checked. Validity of the extracted URL is checked. Also, it is checked if the content is spammy or not.
- Relevant changes have been made to the `extractor.py` and `performance.py` files, as mentioned above.
- Comments have been added to functions in the `perfromance.py` file.
- Changes have been made in the appearance of the application. The frontend now contains links to different routes, so that the user does need to type in the route manually everytime, and a route can be accessed with just a single click. This makes the application more user friendly.
## Related Issue

## Motivation and Context

Lot of data was being fed to the LLM, which was redundant and not in a proper format, which caused the LLM to hallucinate. So it was important to filter out the bad data before storing it into the database. Also, new sources for the news have been added to fetch more information.
## How Has This Been Tested?

## Screenshots (if appropriate):
![Screenshot_20240623_110307](https://github.com/c2siorg/b0bot/assets/121498899/b57a3e2c-3c9a-4acf-ae27-33f3046d0fde)
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-06-24 08:56 UTC, CoToYo requested changes

2024-06-24 08:56 UTC, CoToYo commented on templates/gemma.html
The reason we call a page as "template" is mainly because it is a page that can show different content in a certain structure/format. I see the pages like `gemma.html`, `llama.html` and `mistralai.thml` under `templates` folder are almost the same. Let's use  a single html template for these 3 models. It's not a good idea to create a new similar page for every single models and we may introduce more models into our api in the future.

2024-06-24 08:56 UTC, CoToYo commented on cybernews/performance.py
👍

2024-06-24 10:56 UTC, hardik1408 commented on templates/gemma.html
Alright, I will work upon this.

2024-06-25 09:35 UTC, hardik1408 commented
@CoToYo Did the changes, kindly review.

2024-06-28 05:06 UTC, CoToYo approved these changes

2024-06-28 05:06 UTC, CoToYo commented on static/js/content.js
> +    };
Can we separate these static string data into another directory?

2024-06-29 06:47 UTC, merged